export const LAWYER_STATUS = {
  active: { label: 'Aktif', color: 'text-green-600 bg-green-50 border-green-200' },
  suspended: { label: 'Askıda', color: 'text-amber-600 bg-amber-50 border-amber-200' },
  deleted: { label: 'Silinmiş', color: 'text-red-500 bg-red-50 border-red-200' },
};

export const LISTING_STATUS = {
  active: { label: 'Aktif', color: 'text-green-600 bg-green-50 border-green-200' },
  passive: { label: 'Pasif', color: 'text-gray-500 bg-gray-50 border-gray-200' },
  cancelled: { label: 'İptal', color: 'text-red-500 bg-red-50 border-red-200' },
};

export const APPLICATION_STATUS = {
  pending: { label: 'Beklemede', color: 'text-blue-600 bg-blue-50 border-blue-200' },
  approved: { label: 'Onaylandı', color: 'text-green-600 bg-green-50 border-green-200' },
  rejected: { label: 'Reddedildi', color: 'text-red-500 bg-red-50 border-red-200' },
  cancelled: { label: 'İptal', color: 'text-gray-500 bg-gray-50 border-gray-200' },
};

export const TURKEY_CITIES = [
  "Adana","Adıyaman","Afyonkarahisar","Ağrı","Aksaray","Amasya","Ankara","Antalya",
  "Ardahan","Artvin","Aydın","Balıkesir","Bartın","Batman","Bayburt","Bilecik",
  "Bingöl","Bitlis","Bolu","Burdur","Bursa","Çanakkale","Çankırı","Çorum",
  "Denizli","Diyarbakır","Düzce","Edirne","Elazığ","Erzincan","Erzurum","Eskişehir",
  "Gaziantep","Giresun","Gümüşhane","Hakkari","Hatay","Iğdır","Isparta","İstanbul",
  "İzmir","Kahramanmaraş","Karabük","Karaman","Kars","Kastamonu","Kayseri","Kilis",
  "Kırıkkale","Kırklareli","Kırşehir","Kocaeli","Konya","Kütahya","Malatya","Manisa",
  "Mardin","Mersin","Muğla","Muş","Nevşehir","Niğde","Ordu","Osmaniye",
  "Rize","Sakarya","Samsun","Şanlıurfa","Siirt","Sinop","Sivas","Şırnak",
  "Tekirdağ","Tokat","Trabzon","Tunceli","Uşak","Van","Yalova","Yozgat","Zonguldak"
];

// 81 ilin adliyeleri
export const CITY_COURTHOUSES = {
  "Adana": ["Adana Adliyesi","Ceyhan Adliyesi","Kozan Adliyesi","İmamoğlu Adliyesi","Karaisalı Adliyesi","Karataş Adliyesi","Pozantı Adliyesi","Saimbeyli Adliyesi","Tufanbeyli Adliyesi","Yumurtalık Adliyesi","Aladağ Adliyesi","Feke Adliyesi","Sarıçam Adliyesi","Yüreğir Adliyesi","Çukurova Adliyesi"],
  "Adıyaman": ["Adıyaman Adliyesi","Besni Adliyesi","Kahta Adliyesi","Gölbaşı Adliyesi","Gerger Adliyesi","Samsat Adliyesi","Çelikhan Adliyesi","Tut Adliyesi","Sincik Adliyesi"],
  "Afyonkarahisar": ["Afyonkarahisar Adliyesi","Bolvadin Adliyesi","Çay Adliyesi","Dinar Adliyesi","Emirdağ Adliyesi","İhsaniye Adliyesi","Sandıklı Adliyesi","Sinanpaşa Adliyesi","Sultandağı Adliyesi","Şuhut Adliyesi"],
  "Ağrı": ["Ağrı Adliyesi","Diyadin Adliyesi","Doğubayazıt Adliyesi","Eleşkirt Adliyesi","Hamur Adliyesi","Patnos Adliyesi","Taşlıçay Adliyesi","Tutak Adliyesi"],
  "Aksaray": ["Aksaray Adliyesi","Ağaçören Adliyesi","Eskil Adliyesi","Gülağaç Adliyesi","Güzelyurt Adliyesi","Ortaköy Adliyesi","Sarıyahşi Adliyesi"],
  "Amasya": ["Amasya Adliyesi","Göynücek Adliyesi","Gümüşhacıköy Adliyesi","Merzifon Adliyesi","Suluova Adliyesi","Taşova Adliyesi","Hamamözü Adliyesi"],
  "Ankara": ["Ankara Adliyesi","Ankara Batı Adliyesi","Sincan Adliyesi","Ankara Bölge Adliye Mahkemesi","Polatlı Adliyesi","Beypazarı Adliyesi","Çubuk Adliyesi","Haymana Adliyesi","Kızılcahamam Adliyesi","Nallıhan Adliyesi","Şereflikoçhisar Adliyesi","Ayaş Adliyesi","Bala Adliyesi","Çamlıdere Adliyesi","Elmadağ Adliyesi","Güdül Adliyesi","Kalecik Adliyesi","Evren Adliyesi","Ankara 1. Aile Mahkemesi","Ankara 2. Aile Mahkemesi","Ankara 3. Aile Mahkemesi","Ankara 4. Aile Mahkemesi","Ankara 5. Aile Mahkemesi","Ankara 1. Asliye Hukuk Mahkemesi","Ankara 2. Asliye Hukuk Mahkemesi","Ankara 3. Asliye Hukuk Mahkemesi","Ankara 1. Asliye Ceza Mahkemesi","Ankara 2. Asliye Ceza Mahkemesi","Ankara 3. Asliye Ceza Mahkemesi","Ankara 1. Ağır Ceza Mahkemesi","Ankara 2. Ağır Ceza Mahkemesi","Ankara 1. İcra Hukuk Mahkemesi","Ankara 2. İcra Hukuk Mahkemesi","Ankara 1. Sulh Hukuk Mahkemesi","Ankara 2. Sulh Hukuk Mahkemesi","Ankara 1. Tüketici Mahkemesi","Ankara 2. Tüketici Mahkemesi","Ankara 1. İş Mahkemesi","Ankara 2. İş Mahkemesi","Ankara 3. İş Mahkemesi","Ankara 1. Fikri ve Sınai Haklar Mahkemesi","Ankara İdare Mahkemesi","Ankara Vergi Mahkemesi"],
  "Antalya": ["Antalya Adliyesi","Antalya Bölge Adliye Mahkemesi","Alanya Adliyesi","Manavgat Adliyesi","Serik Adliyesi","Kumluca Adliyesi","Kemer Adliyesi","Kaş Adliyesi","Finike Adliyesi","Elmalı Adliyesi","Korkuteli Adliyesi","Gazipaşa Adliyesi","Akseki Adliyesi","Gündoğmuş Adliyesi","İbradı Adliyesi"],
  "Ardahan": ["Ardahan Adliyesi","Çıldır Adliyesi","Göle Adliyesi","Hanak Adliyesi","Posof Adliyesi","Damal Adliyesi"],
  "Artvin": ["Artvin Adliyesi","Ardanuç Adliyesi","Arhavi Adliyesi","Borçka Adliyesi","Hopa Adliyesi","Şavşat Adliyesi","Yusufeli Adliyesi","Murgul Adliyesi"],
  "Aydın": ["Aydın Adliyesi","Nazilli Adliyesi","Söke Adliyesi","Kuşadası Adliyesi","Didim Adliyesi","Çine Adliyesi","Germencik Adliyesi","İncirliova Adliyesi","Karacasu Adliyesi","Koçarlı Adliyesi","Sultanhisar Adliyesi","Yenipazar Adliyesi","Buharkent Adliyesi","Kuyucak Adliyesi","Bozdoğan Adliyesi"],
  "Balıkesir": ["Balıkesir Adliyesi","Bandırma Adliyesi","Edremit Adliyesi","Gönen Adliyesi","Burhaniye Adliyesi","Ayvalık Adliyesi","Bigadiç Adliyesi","Dursunbey Adliyesi","Erdek Adliyesi","Havran Adliyesi","İvrindi Adliyesi","Kepsut Adliyesi","Manyas Adliyesi","Savaştepe Adliyesi","Sındırgı Adliyesi","Susurluk Adliyesi"],
  "Bartın": ["Bartın Adliyesi","Amasra Adliyesi","Kurucaşile Adliyesi","Ulus Adliyesi"],
  "Batman": ["Batman Adliyesi","Beşiri Adliyesi","Gercüş Adliyesi","Hasankeyf Adliyesi","Kozluk Adliyesi","Sason Adliyesi"],
  "Bayburt": ["Bayburt Adliyesi","Aydıntepe Adliyesi","Demirözü Adliyesi"],
  "Bilecik": ["Bilecik Adliyesi","Bozüyük Adliyesi","Gölpazarı Adliyesi","Osmaneli Adliyesi","Pazaryeri Adliyesi","Söğüt Adliyesi","İnhisar Adliyesi","Yenipazar Adliyesi"],
  "Bingöl": ["Bingöl Adliyesi","Genç Adliyesi","Karlıova Adliyesi","Kiğı Adliyesi","Solhan Adliyesi","Adaklı Adliyesi","Yayladere Adliyesi","Yedisu Adliyesi"],
  "Bitlis": ["Bitlis Adliyesi","Ahlat Adliyesi","Adilcevaz Adliyesi","Güroymak Adliyesi","Hizan Adliyesi","Mutki Adliyesi","Tatvan Adliyesi"],
  "Bolu": ["Bolu Adliyesi","Gerede Adliyesi","Göynük Adliyesi","Mengen Adliyesi","Mudurnu Adliyesi","Seben Adliyesi","Dörtdivan Adliyesi","Kıbrıscık Adliyesi","Yeniçağa Adliyesi"],
  "Burdur": ["Burdur Adliyesi","Ağlasun Adliyesi","Bucak Adliyesi","Gölhisar Adliyesi","Tefenni Adliyesi","Yeşilova Adliyesi","Çavdır Adliyesi","Çeltikçi Adliyesi","Karamanlı Adliyesi","Kemer Adliyesi","Altınyayla Adliyesi"],
  "Bursa": ["Bursa Adliyesi","Bursa Bölge Adliye Mahkemesi","İnegöl Adliyesi","Gemlik Adliyesi","Karacabey Adliyesi","Mudanya Adliyesi","Mustafakemalpaşa Adliyesi","Orhangazi Adliyesi","Yenişehir Adliyesi","İznik Adliyesi","Keles Adliyesi","Orhaneli Adliyesi","Büyükorhan Adliyesi","Harmancık Adliyesi"],
  "Çanakkale": ["Çanakkale Adliyesi","Biga Adliyesi","Çan Adliyesi","Gelibolu Adliyesi","Ayvacık Adliyesi","Bayramiç Adliyesi","Eceabat Adliyesi","Ezine Adliyesi","Lapseki Adliyesi","Yenice Adliyesi","Bozcaada Adliyesi","Gökçeada Adliyesi"],
  "Çankırı": ["Çankırı Adliyesi","Çerkeş Adliyesi","Ilgaz Adliyesi","Kurşunlu Adliyesi","Orta Adliyesi","Şabanözü Adliyesi","Yapraklı Adliyesi","Atkaracalar Adliyesi","Bayramören Adliyesi","Eldivan Adliyesi","Kızılırmak Adliyesi","Korgun Adliyesi"],
  "Çorum": ["Çorum Adliyesi","Alaca Adliyesi","Bayat Adliyesi","İskilip Adliyesi","Kargı Adliyesi","Mecitözü Adliyesi","Osmancık Adliyesi","Sungurlu Adliyesi","Boğazkale Adliyesi","Uğurludağ Adliyesi","Dodurga Adliyesi","Laçin Adliyesi","Oğuzlar Adliyesi","Ortaköy Adliyesi"],
  "Denizli": ["Denizli Adliyesi","Acıpayam Adliyesi","Buldan Adliyesi","Çal Adliyesi","Çameli Adliyesi","Çivril Adliyesi","Güney Adliyesi","Honaz Adliyesi","Sarayköy Adliyesi","Tavas Adliyesi","Babadağ Adliyesi","Bekilli Adliyesi","Beyağaç Adliyesi","Bozkurt Adliyesi","Kale Adliyesi","Serinhisar Adliyesi"],
  "Diyarbakır": ["Diyarbakır Adliyesi","Diyarbakır Bölge Adliye Mahkemesi","Bismil Adliyesi","Çermik Adliyesi","Çınar Adliyesi","Dicle Adliyesi","Ergani Adliyesi","Hani Adliyesi","Hazro Adliyesi","Kulp Adliyesi","Lice Adliyesi","Silvan Adliyesi","Eğil Adliyesi","Kocaköy Adliyesi","Çüngüş Adliyesi"],
  "Düzce": ["Düzce Adliyesi","Akçakoca Adliyesi","Gölyaka Adliyesi","Gümüşova Adliyesi","Kaynaşlı Adliyesi","Yığılca Adliyesi","Cumayeri Adliyesi","Çilimli Adliyesi"],
  "Edirne": ["Edirne Adliyesi","Havsa Adliyesi","İpsala Adliyesi","Keşan Adliyesi","Lalapaşa Adliyesi","Meriç Adliyesi","Süloğlu Adliyesi","Uzunköprü Adliyesi","Enez Adliyesi"],
  "Elazığ": ["Elazığ Adliyesi","Ağın Adliyesi","Baskil Adliyesi","Karakoçan Adliyesi","Keban Adliyesi","Kovancılar Adliyesi","Maden Adliyesi","Palu Adliyesi","Sivrice Adliyesi","Arıcak Adliyesi","Alacakaya Adliyesi"],
  "Erzincan": ["Erzincan Adliyesi","Çayırlı Adliyesi","İliç Adliyesi","Kemah Adliyesi","Kemaliye Adliyesi","Refahiye Adliyesi","Tercan Adliyesi","Üzümlü Adliyesi","Otlukbeli Adliyesi"],
  "Erzurum": ["Erzurum Adliyesi","Erzurum Bölge Adliye Mahkemesi","Aşkale Adliyesi","Çat Adliyesi","Hınıs Adliyesi","Horasan Adliyesi","İspir Adliyesi","Karayazı Adliyesi","Narman Adliyesi","Oltu Adliyesi","Olur Adliyesi","Pasinler Adliyesi","Şenkaya Adliyesi","Tekman Adliyesi","Tortum Adliyesi","Karaçoban Adliyesi","Uzundere Adliyesi","Pazaryolu Adliyesi","Köprüköy Adliyesi","Aziziye Adliyesi"],
  "Eskişehir": ["Eskişehir Adliyesi","Çifteler Adliyesi","Mahmudiye Adliyesi","Mihalıççık Adliyesi","Sarıcakaya Adliyesi","Seyitgazi Adliyesi","Sivrihisar Adliyesi","Alpu Adliyesi","Beylikova Adliyesi","Günyüzü Adliyesi","Han Adliyesi","İnönü Adliyesi","Mihalgazi Adliyesi"],
  "Gaziantep": ["Gaziantep Adliyesi","Gaziantep Bölge Adliye Mahkemesi","İslahiye Adliyesi","Nizip Adliyesi","Oğuzeli Adliyesi","Araban Adliyesi","Yavuzeli Adliyesi","Karkamış Adliyesi","Nurdağı Adliyesi"],
  "Giresun": ["Giresun Adliyesi","Alucra Adliyesi","Bulancak Adliyesi","Dereli Adliyesi","Espiye Adliyesi","Eynesil Adliyesi","Görele Adliyesi","Keşap Adliyesi","Şebinkarahisar Adliyesi","Tirebolu Adliyesi","Piraziz Adliyesi","Güce Adliyesi","Çamoluk Adliyesi","Çanakçı Adliyesi","Doğankent Adliyesi","Yağlıdere Adliyesi"],
  "Gümüşhane": ["Gümüşhane Adliyesi","Kelkit Adliyesi","Şiran Adliyesi","Torul Adliyesi","Köse Adliyesi","Kürtün Adliyesi"],
  "Hakkari": ["Hakkari Adliyesi","Çukurca Adliyesi","Şemdinli Adliyesi","Yüksekova Adliyesi","Derecik Adliyesi"],
  "Hatay": ["Hatay Adliyesi","Antakya Adliyesi","İskenderun Adliyesi","Dörtyol Adliyesi","Kırıkhan Adliyesi","Reyhanlı Adliyesi","Samandağ Adliyesi","Altınözü Adliyesi","Hassa Adliyesi","Kumlu Adliyesi","Yayladağı Adliyesi","Erzin Adliyesi","Belen Adliyesi","Payas Adliyesi"],
  "Iğdır": ["Iğdır Adliyesi","Aralık Adliyesi","Karakoyunlu Adliyesi","Tuzluca Adliyesi"],
  "Isparta": ["Isparta Adliyesi","Atabey Adliyesi","Eğirdir Adliyesi","Gelendost Adliyesi","Gönen Adliyesi","Keçiborlu Adliyesi","Senirkent Adliyesi","Sütçüler Adliyesi","Şarkikaraağaç Adliyesi","Uluborlu Adliyesi","Yalvaç Adliyesi","Aksu Adliyesi","Yenişarbademli Adliyesi"],
  "İstanbul": ["İstanbul Adliyesi","İstanbul Anadolu Adliyesi","İstanbul Bölge Adliye Mahkemesi","Bakırköy Adliyesi","Büyükçekmece Adliyesi","Çatalca Adliyesi","Gaziosmanpaşa Adliyesi","Küçükçekmece Adliyesi","Silivri Adliyesi","Şişli Adliyesi","Beykoz Adliyesi","Kadıköy Adliyesi","Kartal Adliyesi","Pendik Adliyesi","Sultanbeyli Adliyesi","Tuzla Adliyesi","Ümraniye Adliyesi","Üsküdar Adliyesi","İstanbul 1. Aile Mahkemesi","İstanbul 2. Aile Mahkemesi","İstanbul 1. Asliye Hukuk Mahkemesi","İstanbul 2. Asliye Hukuk Mahkemesi","İstanbul 1. Asliye Ceza Mahkemesi","İstanbul 1. Ağır Ceza Mahkemesi","İstanbul 2. Ağır Ceza Mahkemesi","İstanbul 1. İcra Hukuk Mahkemesi","İstanbul 1. Sulh Hukuk Mahkemesi","İstanbul 1. Tüketici Mahkemesi","İstanbul 1. İş Mahkemesi","İstanbul 1. Fikri ve Sınai Haklar Mahkemesi","İstanbul İdare Mahkemesi","İstanbul Vergi Mahkemesi"],
  "İzmir": ["İzmir Adliyesi","İzmir Bölge Adliye Mahkemesi","Aliağa Adliyesi","Bayındır Adliyesi","Bergama Adliyesi","Bornova Adliyesi","Çeşme Adliyesi","Dikili Adliyesi","Foça Adliyesi","Karaburun Adliyesi","Karşıyaka Adliyesi","Kemalpaşa Adliyesi","Kiraz Adliyesi","Menemen Adliyesi","Ödemiş Adliyesi","Seferihisar Adliyesi","Selçuk Adliyesi","Tire Adliyesi","Torbalı Adliyesi","Urla Adliyesi","Beydağ Adliyesi","Bayraklı Adliyesi","Çiğli Adliyesi","Gaziemir Adliyesi","Güzelbahçe Adliyesi","Menderes Adliyesi","Narlıdere Adliyesi"],
  "Kahramanmaraş": ["Kahramanmaraş Adliyesi","Afşin Adliyesi","Andırın Adliyesi","Çağlayancerit Adliyesi","Ekinözü Adliyesi","Elbistan Adliyesi","Göksun Adliyesi","Nurhak Adliyesi","Pazarcık Adliyesi","Türkoğlu Adliyesi"],
  "Karabük": ["Karabük Adliyesi","Eflani Adliyesi","Eskipazar Adliyesi","Ovacık Adliyesi","Safranbolu Adliyesi","Yenice Adliyesi"],
  "Karaman": ["Karaman Adliyesi","Ayrancı Adliyesi","Başyayla Adliyesi","Ermenek Adliyesi","Kazımkarabekir Adliyesi","Sarıveliler Adliyesi"],
  "Kars": ["Kars Adliyesi","Arpaçay Adliyesi","Digor Adliyesi","Kağızman Adliyesi","Sarıkamış Adliyesi","Selim Adliyesi","Susuz Adliyesi","Akyaka Adliyesi"],
  "Kastamonu": ["Kastamonu Adliyesi","Araç Adliyesi","Cide Adliyesi","Çatalzeytin Adliyesi","Daday Adliyesi","Devrekani Adliyesi","İnebolu Adliyesi","Küre Adliyesi","Taşköprü Adliyesi","Tosya Adliyesi","İhsangazi Adliyesi","Pınarbaşı Adliyesi","Şenpazar Adliyesi","Abana Adliyesi","Ağlı Adliyesi","Azdavay Adliyesi","Bozkurt Adliyesi","Doğanyurt Adliyesi","Hanönü Adliyesi","Seydiler Adliyesi"],
  "Kayseri": ["Kayseri Adliyesi","Kayseri Bölge Adliye Mahkemesi","Bünyan Adliyesi","Develi Adliyesi","Felahiye Adliyesi","İncesu Adliyesi","Pınarbaşı Adliyesi","Sarıoğlan Adliyesi","Sarız Adliyesi","Tomarza Adliyesi","Yahyalı Adliyesi","Yeşilhisar Adliyesi","Akkışla Adliyesi","Özvatan Adliyesi","Hacılar Adliyesi","Talas Adliyesi"],
  "Kilis": ["Kilis Adliyesi","Elbeyli Adliyesi","Musabeyli Adliyesi","Polateli Adliyesi"],
  "Kırıkkale": ["Kırıkkale Adliyesi","Bahşılı Adliyesi","Balışeyh Adliyesi","Çelebi Adliyesi","Delice Adliyesi","Karakeçili Adliyesi","Keskin Adliyesi","Sulakyurt Adliyesi","Yahşihan Adliyesi"],
  "Kırklareli": ["Kırklareli Adliyesi","Babaeski Adliyesi","Demirköy Adliyesi","Kofçaz Adliyesi","Lüleburgaz Adliyesi","Pehlivanköy Adliyesi","Pınarhisar Adliyesi","Vize Adliyesi"],
  "Kırşehir": ["Kırşehir Adliyesi","Akçakent Adliyesi","Akpınar Adliyesi","Boztepe Adliyesi","Çiçekdağı Adliyesi","Kaman Adliyesi","Mucur Adliyesi"],
  "Kocaeli": ["Kocaeli Adliyesi","Gebze Adliyesi","Gölcük Adliyesi","Kandıra Adliyesi","Karamürsel Adliyesi","Körfez Adliyesi","Darıca Adliyesi","Dilovası Adliyesi","Çayırova Adliyesi","Başiskele Adliyesi","Kartepe Adliyesi","Derince Adliyesi"],
  "Konya": ["Konya Adliyesi","Konya Bölge Adliye Mahkemesi","Akşehir Adliyesi","Beyşehir Adliyesi","Bozkır Adliyesi","Cihanbeyli Adliyesi","Çumra Adliyesi","Doğanhisar Adliyesi","Ereğli Adliyesi","Hadim Adliyesi","Ilgın Adliyesi","Kadınhanı Adliyesi","Karapınar Adliyesi","Kulu Adliyesi","Sarayönü Adliyesi","Seydişehir Adliyesi","Yunak Adliyesi","Hüyük Adliyesi","Taşkent Adliyesi","Tuzlukçu Adliyesi","Altınekin Adliyesi","Derebucak Adliyesi","Güneysınır Adliyesi","Halkapınar Adliyesi","Emirgazi Adliyesi","Çeltik Adliyesi","Derbent Adliyesi","Ahırlı Adliyesi","Yalıhüyük Adliyesi"],
  "Kütahya": ["Kütahya Adliyesi","Altıntaş Adliyesi","Domaniç Adliyesi","Emet Adliyesi","Gediz Adliyesi","Simav Adliyesi","Tavşanlı Adliyesi","Aslanapa Adliyesi","Çavdarhisar Adliyesi","Dumlupınar Adliyesi","Hisarcık Adliyesi","Pazarlar Adliyesi","Şaphane Adliyesi"],
  "Malatya": ["Malatya Adliyesi","Akçadağ Adliyesi","Arapgir Adliyesi","Arguvan Adliyesi","Darende Adliyesi","Doğanşehir Adliyesi","Hekimhan Adliyesi","Pütürge Adliyesi","Yeşilyurt Adliyesi","Battalgazi Adliyesi","Doğanyol Adliyesi","Kale Adliyesi","Kuluncak Adliyesi","Yazıhan Adliyesi"],
  "Manisa": ["Manisa Adliyesi","Akhisar Adliyesi","Alaşehir Adliyesi","Demirci Adliyesi","Gördes Adliyesi","Kırkağaç Adliyesi","Kula Adliyesi","Salihli Adliyesi","Sarıgöl Adliyesi","Saruhanlı Adliyesi","Selendi Adliyesi","Soma Adliyesi","Turgutlu Adliyesi","Ahmetli Adliyesi","Gölmarmara Adliyesi","Köprübaşı Adliyesi","Şehzadeler Adliyesi","Yunusemre Adliyesi"],
  "Mardin": ["Mardin Adliyesi","Derik Adliyesi","Kızıltepe Adliyesi","Mazıdağı Adliyesi","Midyat Adliyesi","Nusaybin Adliyesi","Ömerli Adliyesi","Savur Adliyesi","Dargeçit Adliyesi","Yeşilli Adliyesi"],
  "Mersin": ["Mersin Adliyesi","Mersin Bölge Adliye Mahkemesi","Anamur Adliyesi","Erdemli Adliyesi","Gülnar Adliyesi","Mut Adliyesi","Silifke Adliyesi","Tarsus Adliyesi","Aydıncık Adliyesi","Bozyazı Adliyesi","Çamlıyayla Adliyesi","Mezitli Adliyesi","Yenişehir Adliyesi","Toroslar Adliyesi","Akdeniz Adliyesi"],
  "Muğla": ["Muğla Adliyesi","Bodrum Adliyesi","Datça Adliyesi","Fethiye Adliyesi","Köyceğiz Adliyesi","Marmaris Adliyesi","Milas Adliyesi","Ula Adliyesi","Yatağan Adliyesi","Dalaman Adliyesi","Ortaca Adliyesi","Kavaklıdere Adliyesi","Menteşe Adliyesi","Seydikemer Adliyesi"],
  "Muş": ["Muş Adliyesi","Bulanık Adliyesi","Hasköy Adliyesi","Korkut Adliyesi","Malazgirt Adliyesi","Varto Adliyesi"],
  "Nevşehir": ["Nevşehir Adliyesi","Avanos Adliyesi","Derinkuyu Adliyesi","Gülşehir Adliyesi","Hacıbektaş Adliyesi","Kozaklı Adliyesi","Ürgüp Adliyesi","Acıgöl Adliyesi"],
  "Niğde": ["Niğde Adliyesi","Bor Adliyesi","Çamardı Adliyesi","Ulukışla Adliyesi","Altunhisar Adliyesi","Çiftlik Adliyesi"],
  "Ordu": ["Ordu Adliyesi","Akkuş Adliyesi","Aybastı Adliyesi","Fatsa Adliyesi","Gölköy Adliyesi","Korgan Adliyesi","Kumru Adliyesi","Mesudiye Adliyesi","Perşembe Adliyesi","Ulubey Adliyesi","Ünye Adliyesi","Gülyalı Adliyesi","Gürgentepe Adliyesi","Çamaş Adliyesi","Çatalpınar Adliyesi","Çaybaşı Adliyesi","İkizce Adliyesi","Kabadüz Adliyesi","Kabataş Adliyesi"],
  "Osmaniye": ["Osmaniye Adliyesi","Bahçe Adliyesi","Düziçi Adliyesi","Hasanbeyli Adliyesi","Kadirli Adliyesi","Sumbas Adliyesi","Toprakkale Adliyesi"],
  "Rize": ["Rize Adliyesi","Ardeşen Adliyesi","Çamlıhemşin Adliyesi","Çayeli Adliyesi","Fındıklı Adliyesi","Güneysu Adliyesi","Hemşin Adliyesi","İkizdere Adliyesi","İyidere Adliyesi","Kalkandere Adliyesi","Pazar Adliyesi","Derepazarı Adliyesi"],
  "Sakarya": ["Sakarya Adliyesi","Akyazı Adliyesi","Geyve Adliyesi","Hendek Adliyesi","Karasu Adliyesi","Kaynarca Adliyesi","Sapanca Adliyesi","Kocaali Adliyesi","Pamukova Adliyesi","Taraklı Adliyesi","Ferizli Adliyesi","Karapürçek Adliyesi","Söğütlü Adliyesi","Adapazarı Adliyesi","Arifiye Adliyesi","Erenler Adliyesi","Serdivan Adliyesi"],
  "Samsun": ["Samsun Adliyesi","Samsun Bölge Adliye Mahkemesi","Alaçam Adliyesi","Bafra Adliyesi","Çarşamba Adliyesi","Havza Adliyesi","Kavak Adliyesi","Ladik Adliyesi","Terme Adliyesi","Vezirköprü Adliyesi","Asarcık Adliyesi","Ayvacık Adliyesi","Salıpazarı Adliyesi","Tekkeköy Adliyesi","Ondokuzmayıs Adliyesi","Canik Adliyesi","İlkadım Adliyesi","Atakum Adliyesi","Yakakent Adliyesi"],
  "Şanlıurfa": ["Şanlıurfa Adliyesi","Akçakale Adliyesi","Birecik Adliyesi","Bozova Adliyesi","Ceylanpınar Adliyesi","Halfeti Adliyesi","Hilvan Adliyesi","Siverek Adliyesi","Suruç Adliyesi","Viranşehir Adliyesi","Harran Adliyesi","Eyyübiye Adliyesi","Haliliye Adliyesi","Karaköprü Adliyesi"],
  "Siirt": ["Siirt Adliyesi","Baykan Adliyesi","Eruh Adliyesi","Kurtalan Adliyesi","Pervari Adliyesi","Şirvan Adliyesi","Tillo Adliyesi"],
  "Sinop": ["Sinop Adliyesi","Ayancık Adliyesi","Boyabat Adliyesi","Durağan Adliyesi","Erfelek Adliyesi","Gerze Adliyesi","Türkeli Adliyesi","Dikmen Adliyesi","Saraydüzü Adliyesi"],
  "Sivas": ["Sivas Adliyesi","Divriği Adliyesi","Gemerek Adliyesi","Gürün Adliyesi","Hafik Adliyesi","İmranlı Adliyesi","Kangal Adliyesi","Koyulhisar Adliyesi","Suşehri Adliyesi","Şarkışla Adliyesi","Yıldızeli Adliyesi","Zara Adliyesi","Altınyayla Adliyesi","Doğanşar Adliyesi","Gölova Adliyesi","Ulaş Adliyesi","Akıncılar Adliyesi"],
  "Şırnak": ["Şırnak Adliyesi","Beytüşşebap Adliyesi","Cizre Adliyesi","İdil Adliyesi","Silopi Adliyesi","Uludere Adliyesi","Güçlükonak Adliyesi"],
  "Tekirdağ": ["Tekirdağ Adliyesi","Çerkezköy Adliyesi","Çorlu Adliyesi","Hayrabolu Adliyesi","Malkara Adliyesi","Muratlı Adliyesi","Saray Adliyesi","Şarköy Adliyesi","Marmaraereğlisi Adliyesi","Kapaklı Adliyesi","Ergene Adliyesi","Süleymanpaşa Adliyesi"],
  "Tokat": ["Tokat Adliyesi","Almus Adliyesi","Artova Adliyesi","Erbaa Adliyesi","Niksar Adliyesi","Reşadiye Adliyesi","Turhal Adliyesi","Zile Adliyesi","Pazar Adliyesi","Yeşilyurt Adliyesi","Başçiftlik Adliyesi","Sulusaray Adliyesi"],
  "Trabzon": ["Trabzon Adliyesi","Trabzon Bölge Adliye Mahkemesi","Akçaabat Adliyesi","Araklı Adliyesi","Arsin Adliyesi","Çaykara Adliyesi","Maçka Adliyesi","Of Adliyesi","Sürmene Adliyesi","Tonya Adliyesi","Vakfıkebir Adliyesi","Yomra Adliyesi","Beşikdüzü Adliyesi","Şalpazarı Adliyesi","Çarşıbaşı Adliyesi","Dernekpazarı Adliyesi","Düzköy Adliyesi","Hayrat Adliyesi","Köprübaşı Adliyesi","Ortahisar Adliyesi"],
  "Tunceli": ["Tunceli Adliyesi","Çemişgezek Adliyesi","Hozat Adliyesi","Mazgirt Adliyesi","Nazımiye Adliyesi","Ovacık Adliyesi","Pertek Adliyesi","Pülümür Adliyesi"],
  "Uşak": ["Uşak Adliyesi","Banaz Adliyesi","Eşme Adliyesi","Karahallı Adliyesi","Sivaslı Adliyesi","Ulubey Adliyesi"],
  "Van": ["Van Adliyesi","Başkale Adliyesi","Çaldıran Adliyesi","Çatak Adliyesi","Erciş Adliyesi","Gevaş Adliyesi","Gürpınar Adliyesi","Muradiye Adliyesi","Özalp Adliyesi","Saray Adliyesi","Bahçesaray Adliyesi","Edremit Adliyesi","İpekyolu Adliyesi","Tuşba Adliyesi"],
  "Yalova": ["Yalova Adliyesi","Altınova Adliyesi","Armutlu Adliyesi","Çınarcık Adliyesi","Çiftlikköy Adliyesi","Termal Adliyesi"],
  "Yozgat": ["Yozgat Adliyesi","Akdağmadeni Adliyesi","Boğazlıyan Adliyesi","Çayıralan Adliyesi","Çekerek Adliyesi","Sarıkaya Adliyesi","Şefaatli Adliyesi","Sorgun Adliyesi","Yerköy Adliyesi","Aydıncık Adliyesi","Çandır Adliyesi","Kadışehri Adliyesi","Saraykent Adliyesi","Yenifakılı Adliyesi"],
  "Zonguldak": ["Zonguldak Adliyesi","Çaycuma Adliyesi","Devrek Adliyesi","Ereğli Adliyesi","Alaplı Adliyesi","Gökçebey Adliyesi","Kilimli Adliyesi","Kozlu Adliyesi"]
};

// Yardımcı: Şehre göre adliyeleri getir
export function getCourthousesByCity(city) {
  return CITY_COURTHOUSES[city] || [];
}
